
// >>THIS FILE IS AUTO GENERATED<< (DON'T MODIFY ITS CONTENT)
#include "ASTCustomAttributes.hpp"

#define REGISTER_AST(AST_CLASS) if (const auto *const p = dynamic_cast<const AST_CLASS*>(ast)) return GetCustomAttributesImpl(p);


std::vector<Attribute> GetCustomAttributes(const DB::IAST* ast) {
    REGISTER_AST(DB::ASTAlterNamedCollectionQuery)
    // REGISTER_AST(DB::ASTAlterQuery)
    REGISTER_AST(DB::ASTAssignment)
    // REGISTER_AST(DB::ASTAsterisk)
    // REGISTER_AST(DB::ASTBackupQuery)
    // REGISTER_AST(DB::ASTCheckQuery)
    // REGISTER_AST(DB::ASTCollation)
    REGISTER_AST(DB::ASTColumnDeclaration)
    // REGISTER_AST(DB::ASTColumnsMatcher)
    // REGISTER_AST(DB::ASTColumnsTransformers)
    REGISTER_AST(DB::ASTConstraintDeclaration)
    REGISTER_AST(DB::ASTCreateFunctionQuery)
    REGISTER_AST(DB::ASTCreateIndexQuery)
    REGISTER_AST(DB::ASTCreateNamedCollectionQuery)
    REGISTER_AST(DB::ASTCreateQuery)
    REGISTER_AST(DB::ASTDatabaseOrNone)
    // REGISTER_AST(DB::ASTDeleteQuery)
    REGISTER_AST(DB::ASTDescribeCacheQuery)
    REGISTER_AST(DB::ASTDictionaryAttributeDeclaration)
    // REGISTER_AST(DB::ASTDictionary)
    REGISTER_AST(DB::ASTDropFunctionQuery)
    REGISTER_AST(DB::ASTDropIndexQuery)
    REGISTER_AST(DB::ASTDropNamedCollectionQuery)
    REGISTER_AST(DB::ASTDropQuery)
    // REGISTER_AST(DB::ASTExplainQuery)
    REGISTER_AST(DB::ASTExpressionList)
    // REGISTER_AST(DB::ASTExternalDDLQuery)
    REGISTER_AST(DB::ASTForeignKeyDeclaration)
    REGISTER_AST(DB::ASTFunction)
    REGISTER_AST(DB::ASTFunctionWithKeyValueArguments)
    // REGISTER_AST(DB::ASTHelpers)
    // REGISTER_AST(DB::ASTIdentifier_fwd)
    REGISTER_AST(DB::ASTIdentifier)
    REGISTER_AST(DB::ASTIndexDeclaration)
    REGISTER_AST(DB::ASTInsertQuery)
    REGISTER_AST(DB::ASTInterpolateElement)
    REGISTER_AST(DB::ASTKillQueryQuery)
    REGISTER_AST(DB::ASTLiteral)
    REGISTER_AST(DB::ASTNameTypePair)
    REGISTER_AST(DB::ASTOptimizeQuery)
    REGISTER_AST(DB::ASTOrderByElement)
    REGISTER_AST(DB::ASTPartition)
    REGISTER_AST(DB::ASTProjectionDeclaration)
    // REGISTER_AST(DB::ASTProjectionSelectQuery)
    // REGISTER_AST(DB::ASTQualifiedAsterisk)
    REGISTER_AST(DB::ASTQueryParameter)
    REGISTER_AST(DB::ASTQueryWithOnCluster)
    REGISTER_AST(DB::ASTQueryWithOutput)
    REGISTER_AST(DB::ASTQueryWithTableAndOutput)
    // REGISTER_AST(DB::ASTRefreshStrategy)
    REGISTER_AST(DB::ASTRenameQuery)
    // REGISTER_AST(DB::ASTSampleRatio)
    // REGISTER_AST(DB::ASTSelectIntersectExceptQuery)
    REGISTER_AST(DB::ASTSelectQuery)
    REGISTER_AST(DB::ASTSelectWithUnionQuery)
    REGISTER_AST(DB::ASTSetQuery)
    REGISTER_AST(DB::ASTShowColumnsQuery)
    // REGISTER_AST(DB::ASTShowEngineQuery)
    // REGISTER_AST(DB::ASTShowFunctionsQuery)
    REGISTER_AST(DB::ASTShowIndexesQuery)
    // REGISTER_AST(DB::ASTShowProcesslistQuery)
    // REGISTER_AST(DB::ASTShowSettingQuery)
    REGISTER_AST(DB::ASTShowTablesQuery)
    // REGISTER_AST(DB::ASTSQLSecurity)
    // REGISTER_AST(DB::ASTStatisticsDeclaration)
    REGISTER_AST(DB::ASTSubquery)
    REGISTER_AST(DB::ASTSystemQuery)
    REGISTER_AST(DB::ASTTableOverride)
    // REGISTER_AST(DB::ASTTablesInSelectQuery)
    // REGISTER_AST(DB::ASTTimeInterval)
    REGISTER_AST(DB::ASTTransactionControl)
    REGISTER_AST(DB::ASTTTLElement)
    // REGISTER_AST(DB::ASTUndropQuery)
    // REGISTER_AST(DB::ASTUseQuery)
    REGISTER_AST(DB::ASTWatchQuery)
    REGISTER_AST(DB::ASTWindowDefinition)
    REGISTER_AST(DB::ASTWithAlias)
    REGISTER_AST(DB::ASTWithElement)
    return GetCustomAttributesImpl(ast);
}
